# Generated by Django 2.0.12 on 2019-08-13 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('opreate_username', models.CharField(help_text='默认为操作员', max_length=33, verbose_name='操作员')),
                ('remote_addr', models.GenericIPAddressField(default='127.0.0.1', help_text='操作的IP', verbose_name='IP')),
                ('change_name', models.CharField(blank=True, default=None, max_length=155, verbose_name='变更名')),
                ('change_obj', models.CharField(blank=True, default=None, max_length=155, verbose_name='变更对象')),
                ('change_desc', models.CharField(blank=True, default=None, max_length=155, verbose_name='变更描述')),
                ('change_stat', models.CharField(choices=[('APPENDING', '变更中'), ('FAILED', '变更失败'), ('SECCUSS', '变更成功'), ('ROLLING', '变更回滚')], default='SECCUSS', max_length=10, verbose_name='变更状态')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='审计时间')),
            ],
            options={
                'verbose_name': '平台变更记录',
                'db_table': 'change_audit',
                'ordering': ('-date_created',),
            },
        ),
    ]
