# Generated by Django 2.0.12 on 2019-08-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeaudit',
            name='change_desc',
            field=models.CharField(blank=True, default='', max_length=155, verbose_name='变更描述'),
        ),
        migrations.AlterField(
            model_name='changeaudit',
            name='change_name',
            field=models.CharField(blank=True, default='', max_length=155, verbose_name='变更名'),
        ),
        migrations.AlterField(
            model_name='changeaudit',
            name='change_obj',
            field=models.CharField(blank=True, default='', max_length=155, verbose_name='变更对象'),
        ),
    ]
