# Generated by Django 2.0.12 on 2019-08-14 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190813_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_host', models.CharField(default='smtp.163.com', help_text='邮件服务端地址例如smtp.163.com', max_length=255, verbose_name='邮件服务端地址')),
                ('mail_user', models.CharField(help_text='邮件用户名root', max_length=255, verbose_name='邮件用户名')),
                ('mail_pass', models.CharField(help_text='邮件设置的棉麻', max_length=255, verbose_name='邮件用户名')),
                ('mail_postfix', models.CharField(default='163.com', help_text='邮件用户名root', max_length=255, verbose_name='邮件后缀')),
                ('default_recv', models.CharField(default='180573956@qq.com,admin@actanble.com', max_length=255, verbose_name='默认接收者')),
                ('active', models.BooleanField(default=True, verbose_name='生效')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='审计时间')),
            ],
            options={
                'verbose_name': '邮件服务端列表',
                'db_table': 'mail_hosts',
                'ordering': ('active', '-date_created'),
            },
        ),
        migrations.CreateModel(
            name='SnmpHostData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('send_flow', models.FloatField(default=0.0, verbose_name='发送的字节数')),
                ('recv_flow', models.FloatField(default=0.0, verbose_name='接受字节数')),
                ('cpu_percent', models.FloatField(default=0.0, verbose_name='CPU占用')),
                ('mem_percent', models.FloatField(default=0.0, verbose_name='内存占用')),
                ('disk_percent', models.FloatField(default=0.0, verbose_name='硬盘占用')),
                ('up_time', models.IntegerField(blank=True, default=0, verbose_name='开启时间')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='监控时间')),
            ],
            options={
                'verbose_name': 'SNMP部件监控数据',
                'db_table': 'snmp_agent_datas',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='SnmpV2AgentCfgInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('snmp_host', models.GenericIPAddressField(verbose_name='IP')),
                ('snmp_port', models.IntegerField(default=161, verbose_name='Snmp端口')),
                ('snmp_community', models.CharField(max_length=32, verbose_name='Snmp组织密码')),
                ('host_uniq', models.CharField(max_length=122, unique=True, verbose_name='主机唯一ID')),
                ('collected', models.BooleanField(default=True, verbose_name='是否收集')),
            ],
            options={
                'verbose_name': 'SnmpV2配置信息',
                'db_table': 'snmpv2_agent_cfg_info',
            },
        ),
        migrations.DeleteModel(
            name='ChangeAudit',
        ),
    ]
