# Generated by Django 2.0.12 on 2019-08-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190814_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_second', models.CharField(default='0', max_length=10, verbose_name='分')),
                ('cron_minute', models.CharField(default='*/5', max_length=10, verbose_name='分')),
                ('cron_hour', models.CharField(default='*', max_length=10, verbose_name='时')),
                ('cron_day', models.CharField(default='*', max_length=10, verbose_name='天')),
                ('cron_month', models.CharField(default='*', max_length=10, verbose_name='月')),
                ('cron_week', models.CharField(default='*', max_length=10, verbose_name='周')),
                ('cron_name', models.CharField(default='every 5 minute', max_length=100, unique=True, verbose_name='Cron名称')),
            ],
            options={
                'verbose_name': 'Cron配置',
                'db_table': 'opsmanage_cron_config',
            },
        ),
    ]
