# Generated by Django 2.0.12 on 2019-08-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cronconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='log_id')),
                ('job_id', models.CharField(max_length=10, verbose_name='job_id')),
                ('status', models.CharField(max_length=10, verbose_name='task_cmd')),
                ('task_cmd', models.CharField(max_length=150, verbose_name='task_cmd')),
                ('task_log', models.TextField(verbose_name='task_log')),
                ('exec_time', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'Cron执行日志',
                'db_table': 'cron_log',
                'ordering': ('-exec_time',),
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='log_id')),
                ('log_key', models.CharField(max_length=150, verbose_name='log_key')),
                ('task_level', models.IntegerField()),
                ('log_info', models.TextField()),
                ('exec_time', models.BigIntegerField()),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'scheduler_task 执行日志',
                'db_table': 'scheduler_task_log',
                'ordering': ('-log_time', '-task_level'),
            },
        ),
        migrations.AlterField(
            model_name='cronconfig',
            name='cron_minute',
            field=models.CharField(default='*', max_length=10, verbose_name='分'),
        ),
        migrations.AlterField(
            model_name='cronconfig',
            name='cron_name',
            field=models.CharField(default='every 1 second', max_length=100, unique=True, verbose_name='Cron名称'),
        ),
        migrations.AlterField(
            model_name='cronconfig',
            name='cron_second',
            field=models.CharField(default='*', max_length=10, verbose_name='分'),
        ),
    ]
