cookie_secret: nJ2oZis0V/xlArY2rzpIE6ioC9/KlqR2fd59sD=UXZJ=3OeROB
token_secret: pXFb4i%*834gfdh963df713iodGq4dsafsdadg7yI6ImF1999aaG7


MYSQL_HOST: 192.168.2.227
MYSQL_ROOT_USER: root
MYSQL_PASSWORD: test@1q2w2e4R
MYSQL_SERVER_PORT: 33306
MYSQL_SERVER_DB: cso_811

REDIS_HOST: 192.168.2.227
REDIS_PORT: 36379
REDIS_PASSWORD: test@1q2w2e4R

MQ_HOST: 192.168.2.227
MQ_USER: root
MQ_PASSWORD: test@1q2w2e4R


